/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es/components/button/index')['ElButton']
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es/components/date-picker/index')['ElDatePicker']
    ElDialog: typeof import('element-plus/es/components/dialog/index')['ElDialog']
    ElDrawer: typeof import('element-plus/es/components/drawer/index')['ElDrawer']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index')['ElEmpty']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElImageViewer: typeof import('element-plus/es/components/image-viewer/index')['ElImageViewer']
    ElOption: typeof import('element-plus/es/components/select/index')['ElOption']
    ElPagination: typeof import('element-plus/es/components/pagination/index')['ElPagination']
    ElPopover: typeof import('element-plus/es/components/popover/index')['ElPopover']
    ElSelect: typeof import('element-plus/es/components/select/index')['ElSelect']
    ElSkeleton: typeof import('element-plus/es/components/skeleton/index')['ElSkeleton']
    ElTable: typeof import('element-plus/es/components/table/index')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index')['ElTableColumn']
    ElTag: typeof import('element-plus/es/components/tag/index')['ElTag']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
